"""init

Revision ID: a615001313b1
Revises: 
Create Date: 2026-02-20 23:18:43.979646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a615001313b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('dexpay_internal_id', sa.String(length=64), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reg_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('amount_rub', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_usdt', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('network_fee_rub', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_payment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wallet_address', sa.String(length=128), nullable=False),
    sa.Column('network', sa.String(length=20), nullable=False),
    sa.Column('dexpay_order_id', sa.String(length=64), nullable=True),
    sa.Column('payment_link', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dexpay_order_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('users')
    # ### end Alembic commands ###
